### ISSUE TITLE
ClipCrop and ClipSeg throw an error

### ISSUE THREAD

**Issue by pol3et** [Vishnunkumar/clipcrop#4]
```python
from clipcrop import clipcrop as ccr

photo_path = "content/example.png"

clipseg = ccr.ClipSeg(photo_path, "driver's license")
segmentor, clipmodel, clipprocessor = clipseg.load_models()
result = clipseg.segment_image(segmentor, clipmodel, clipprocessor)
```
Running this code throws an error:
```
Traceback (most recent call last):
  File "C:\test\venv\Lib\site-packages\PIL\Image.py", line 3130, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 5), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\test\clipcroptest.py", line 7, in <module>
    result = clipseg.segment_image(segmentor, clipmodel, clipprocessor)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\clipcrop\clipcrop.py", line 283, in segment_image
    respl = Image.fromarray(res)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\PIL\Image.py", line 3134, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 5), |u1
```

Running code snippet for ClipCrop:
```python
from clipcrop import clipcrop as ccr

photo_path = "content/example.png"

cc = ccr.ClipCrop(photo_path)

DFE, DM, CLIPM, CLIPP = cc.load_models()

result = cc.extract_image(DFE, DM, CLIPM, CLIPP, "text content", num=2)
```
results in the following error:
```
Traceback (most recent call last):
  File "c:\test\clipcroptest.py", line 9, in <module>
    result = cc.extract_image(DFE, DM, CLIPM, CLIPP, "text content", num=2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\clipcrop\clipcrop.py", line 164, in extract_image
    inputs = self.CLIPP(text = [self.text], images=images_list , return_tensors="pt", padding=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\transformers\models\clip\processing_clip.py", line 104, in __call__
    image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\transformers\image_processing_utils.py", line 551, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\transformers\models\clip\image_processing_clip.py", line 282, in preprocess
    images = make_list_of_images(images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\transformers\image_utils.py", line 141, in make_list_of_images
    if is_batched(images):
       ^^^^^^^^^^^^^^^^^^
  File "C:\test\venv\Lib\site-packages\transformers\image_utils.py", line 114, in is_batched
    return is_valid_image(img[0])
                          ~~~^^^
IndexError: list index out of range

**Comment by Vishnunkumar** [comment]
Could you please share me the image file?
